# -*- coding: utf-8 -*-
"""compute cosine similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5S3IPDYldvd_Aq1_zoL82cTsbAPNbSs
"""

!pip install sentence-transformers
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from gensim.models import Word2Vec
from sentence_transformers import SentenceTransformer

review_a = 'incredible camera but terrible battery life'
review_b = 'battery drains fast although photos are stunning'
docs = [review_a, review_b]


cv = CountVectorizer()
bow_matrix = cv.fit_transform(docs)
bow_sim = cosine_similarity(bow_matrix[0:1], bow_matrix[1:2])[0][0]


tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(docs)
tfidf_sim = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])[0][0]


sentences = [d.lower().replace(',', '').split() for d in docs]
w2v_model = Word2Vec(sentences, vector_size=100, min_count=1, window=5)

def get_avg_vec(tokens, model):
    vecs = [model.wv[t] for t in tokens if t in model.wv]
    return np.mean(vecs, axis=0) if vecs else np.zeros(100)

w2v_sim = cosine_similarity([get_avg_vec(sentences[0], w2v_model)], [get_avg_vec(sentences[1], w2v_model)])[0][0]


sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = sbert_model.encode(docs)
sbert_sim = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]

print(f'BOW Similarity: {bow_sim:.4f}')
print(f'TF-IDF Similarity: {tfidf_sim:.4f}')
print(f'Word2Vec Avg Similarity: {w2v_sim:.4f}')
print(f'Sentence-BERT Similarity: {sbert_sim:.4f}')
print('\nBOW Vocabulary:', cv.get_feature_names_out())
print('Exact Word Intersection:', set(sentences[0]).intersection(set(sentences[1])))

