# -*- coding: utf-8 -*-
"""word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5S3IPDYldvd_Aq1_zoL82cTsbAPNbSs
"""

!pip install gensim
from gensim.models import Word2Vec
import pandas as pd
import numpy as np


df = pd.read_csv("/content/reviews_sample.csv")


sentences = [text.lower().split() for text in df['review_text'].dropna()]


model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

from numpy import dot
from numpy.linalg import norm

def cosine_similarity(a, b):
    return dot(a, b) / (norm(a) * norm(b))


word1 = 'cheap'
word2 = 'affordable'
word3 = 'flimsy'


fallback_word = model.wv.index_to_key[0]

if word1 in model.wv:
    vec1 = model.wv[word1]
else:
    print(f"Word '{word1}' not in vocabulary. Using '{fallback_word}' instead.")
    vec1 = model.wv[fallback_word]

if word2 in model.wv:
    vec2 = model.wv[word2]
else:
    print(f"Word '{word2}' not in vocabulary. Using '{fallback_word}' instead.")
    vec2 = model.wv[fallback_word]

if word3 in model.wv:
    vec3 = model.wv[word3]
else:
    print(f"Word '{word3}' not in vocabulary. Using '{fallback_word}' instead.")
    vec3 = model.wv[fallback_word]

sim1 = cosine_similarity(vec1, vec2)
sim2 = cosine_similarity(vec1, vec3)

print(f"{word1} vs {word2}:", sim1)
print(f"{word1} vs {word3}:", sim2)

